development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "1098b528134116cc03f84fa98f7e54e749c85b166148e2be3ec7ba6e528b4c85"
  signature_expiration: 3600 # one hour
