# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0e6535062e8421df2db703f47fbe71fb616ce756da6fd3d73911826d884f75e503014ca5a910b9f10686217b07ffe1d88a564d621e698bfdbc47b6f74dfcaaf
  facebook_app_id: 972217322892999
  facebook_app_secret: 9a6b3703969a808e13485f33a8959f41

test:
  secret_key_base: cf44492210dc1d420cfe9136b2d75b38f3bf168cd127878f19516474a2ee1cf3c75314b01377a4c9299c6be794f76fceead132d2e81d1373c27958727a5e9462

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
